### ISSUE TITLE
Could not Find the Datasets

### ISSUE THREAD

**Issue by sebpeterkasi** [mameli/Artifact_Removal_GAN#5]
Greeting!

First of all, thanks for sharing your amazing work. I was trying to recreate the results that you have created but I'm having difficulties finding out those datasets. Would you able to guide me on this? It seems path given based on your workstation directory. 
Hope to hear from you soon!
Thanks

**Comment by mameli** [comment]
Hi @sebpeterkasi 

You can download the training images from [https://data.vision.ee.ethz.ch/cvl/DIV2K/](https://data.vision.ee.ethz.ch/cvl/DIV2K/)

**Comment by sebpeterkasi** [comment]
Hi @mameli 

Thanks for a prompt reply!!!
DIV2K is the link I referred based on your codes and I have downloaded (Train Data HR Images) but I'm having confusing in following datasets you have used such as:-

ffhq_path = Path("/data/students_home/fmameli/repos/ffhq-dataset/images1024x1024") - **Not Found**
div2k = Path("/data/students_home/fmameli/repos/Artifact_Removal_GAN/dataset/DIV2K_train_HR") - **Found**
flickr2k = Path("/data/students_home/fmameli/repos/Artifact_Removal_GAN/dataset/Flickr2K/Flickr2K_HR") - **Not Found**
ffhq_path = Path("/data/students_home/fmameli/repos/ffhq-dataset/images1024x1024") - Not Found

path_lowRes_256 = path/'DIV2K_train_LR_256_QF20' - **Not Found in DIV2K repository**
path_lowRes_512 = path/'DIV2K_train_LR_512_QF20' - **Not Found in DIV2K repository**
path_lowRes_1k = path/'DIV2K_train_LR_1024_QF20' - **Not Found in DIV2K repository**
path_lowRes_Full = path/'DIV2K_train_LR_Full_QF20' - **Not Found in DIV2K repository**

path_lowRes_512_mixed = path/'Flickr2K'/'Flickr2K_LR_512_QF20' - **Not Found**
path_lowRes_1024_mixed = path/'Flickr2K'/'Flickr2K_LR_512_QF20' - **Not Found**
path_lowRes_512_mixed = path/'DIV2K_Flickr_Mixed_LR_512_QF20' - **Not Found**
path_lowRes_1024_mixed = path/'DIV2K_Flickr_Mixed_LR_1024_QF20' - **Not Found**

weights = "/data/students_home/fmameli/repos/Artifact_Removal_GAN/models/unet_wideNf2_mobileV3_DivFlickr1k_P64px_SuperRes_gen_3" - **Not Found**

Not Found meaning either I couldn't find it through DIV2K repository or it's just I couldn't find the source of it.

Please guide me on this.
It would be much appreciated :-)
Hope to hear from you soon!!!

Sebpeterkasi

**Comment by mameli** [comment]
Hi Sebpeterkasi,

For the "standard" model ([link](https://github.com/mameli/Artifact_Removal_GAN/releases/tag/v1.0)) I used only the DIV2K database. For the "minimal" model I used a mix of images from DIV2K, [Flickr2K ](https://cv.snu.ac.kr/research/EDSR/Flickr2K.tar) and [ffhq](https://github.com/NVlabs/ffhq-dataset). 
The main results that you can see in the readme page are from the "standard" model.
You can create the training database using the function create_dataset from [dataset.py](https://github.com/mameli/Artifact_Removal_GAN/blob/master/ArNet/dataset.py) (example [here](https://github.com/mameli/Artifact_Removal_GAN/blob/master/Test_components.ipynb) in dataset setup).
The training images are the high-resolution images from DIV2K compressed through the jpeg technique with 20 quality factor.

DIV2K_train_LR_256_QF20 means images the 256px resolution and 20 quality factor
DIV2K_train_LR_Full_QF20 means images at full resolution and 20 quality factor.

and for the weights, I just uploaded the final weights of the models (excluding the not fully trained ones). So to get the weights of the pre-trained the generator model you have to train the model yourself using [this script](https://github.com/mameli/Artifact_Removal_GAN/blob/master/Training_unet_patch_LPIPS_64.py).

I hope to have answered all your questions :smile:

**Comment by sebpeterkasi** [comment]
Hi @mameli,

That was well explained. I will get to work on that. Thanks a lot mate :-)
